# Configuración de entrenamiento
model: yolov8s.pt
data: configs/senati_dataset.yaml

# Hiperparámetros
epochs: 50
batch: 8
imgsz: 640
patience: 10
device: cpu 

# Salida
project: models/trained
name: senati_v1
exist_ok: true

# Opciones
pretrained: true
verbose: true
save: true
plots: true